# Dataframes mit Merge über gemeinse Spaltennamen zufammenführen

die `Merge`-Methode bietet alle nötigen Join-Methoden an, um Dataframes zusammenzuführen. Sie ist mächtiger als die einfachere `Concat`-Methode aus dem Kapitel davor.

die Merge-Methode erwartet einen linken Dataframe `left`, einen rechten DataFrame `right`, die Angabe der gewüschnter `Join`-Operation und mit `on` die Angabe, auf welcher Spalte bzw. ob auf den Indizies zusammengeführt werden soll.

Grundsätzlich ist es eine gute Idee, Merge zu nutzen, wenn man auf Spaltenbasis zusammenführen will. Für das Zusammenführen auf der Indexmenge gibt es noch die Methode `join`.


## Beispiel
Wir haben zwei DataFrames. `df_left` ist das  linke Dataframe, `df_right` ist das rechte DataFrame. Beide Dataframes teilen eine Spalte gleichen Namens, nämlich `motor`. Wir wollen dieses Dataframe jetzt zu einem Dataframe verbinden und nutzen dazu als gemeinsame Spalte `motor`.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_left = pd.DataFrame({
    "motor": ["A1", "A2", "A3", "A4"],
    "acc": [133, 132, 145, 111],
})


df_right = pd.DataFrame({
    "motor": ["A1", "A2", "A3", "A4"],
    "max": [233, 98, 241, 198],
})

display(df_left)
display(df_right)

  motor  acc
0    A1  133
1    A2  132
2    A3  145
3    A4  111

  motor  max
0    A1  233
1    A2   98
2    A3  241
3    A4  198

In [3]:
# mit dem on-Keyword wird der Spaltenname angegeben, der in beiden DF gleich ist
df_merged = pd.merge(df_left, df_right, on="motor")
display(df_merged)

  motor  acc  max
0    A1  133  233
1    A2  132   98
2    A3  145  241
3    A4  111  198

## Beispiel mit unterschiedlichen Keys
Bei unterschiedlichen Spaltenwerten gehen Daten verloren

In [4]:
df_left2 = pd.DataFrame({
    "motor": ["A1", "A2", "A3", "A5"],
    "acc": [133, 132, 145, 111],
})


df_right2 = pd.DataFrame({
    "motor": ["A1", "A2", "A3", "A4"],
    "max": [233, 98, 241, 198],
})

df_merge_2 = pd.merge(df_left2, df_right2, on="motor") # inner join
display(df_merge_2)

  motor  acc  max
0    A1  133  233
1    A2  132   98
2    A3  145  241

### Left Join, linke Spalte bleibt ganz erhalten
resultiert natürlich in NaN-Werten für die fehlende Zeile

In [5]:
# Left join on motor
df_merged_left = pd.merge(df_left, df_right, on="motor", how="left")
display(df_merged_left)

  motor  acc  max
0    A1  133  233
1    A2  132   98
2    A3  145  241
3    A4  111  198

### Outer Join, beide Spalten bleiben erhalten
resultiert natürlich in NaN-Werten für die fehlende Zeile

In [6]:
# right join on motor
df_merged_right = pd.merge(df_left, df_right, on="motor", how="right")
display(df_merged_right)

  motor  acc  max
0    A1  133  233
1    A2  132   98
2    A3  145  241
3    A4  111  198

# Aufgabe: Bevölkerungszahlen für verschiedene Länder

Führe die beiden Dataframes zusammen und berechne die Bevölkerungsdichte pro Land

In [10]:
import pandas as pd

# Bevölkerungszahlen für verschiedene Länder
data_population = {
    "Land": ["Deutschland", "Frankreich", "Italien", "Spanien"],
    "Bevölkerung": [83000000, 67000000, 60000000, 47000000]
}
df_population = pd.DataFrame(data_population)

# Flächenangaben für verschiedene Länder (in km²)
data_area = {
    "Land": ["Deutschland", "Frankreich", "Italien", "Spanien"],
    "Fläche_km2": [357386, 551695, 301340, 505992]
}
df_area = pd.DataFrame(data_area)

# Führe die Tabellen zusammen
df_merged = pd.merge(df_population, df_area, on="Land")

# Berechne die Bevölkerungsdichte (Einwohner pro km²)
df_merged["km2 x P"] = (df_merged["Bevölkerung"] / df_merged["Fläche_km2"]).round(2)

# style
sty = (
    df_merged.style
        .hide(axis="index")
        .format({
            "Bevölkerung": "{:,.0f}",
            "Fläche_km2": "{:,.0f}",
            "km2 x P": "{:,.2f}",
        })
)



# Ausgabe des Ergebnisses
print("Zusammengeführte Tabelle mit Bevölkerungsdichte:")
display(sty)

Zusammengeführte Tabelle mit Bevölkerungsdichte:

### **Erwartete Ausgabe**

| Land        | Bevölkerung | Fläche (km²) | Bevölkerungsdichte (Einwohner/km²) |
|-------------|-------------|--------------|----------------------------------|
| Deutschland | 83,000,000  | 357,386      | 232.25                           |
| Frankreich  | 67,000,000  | 551,695      | 121.46                           |
| Italien     | 60,000,000  | 301,340      | 199.12                           |
| Spanien     | 47,000,000  | 505,992      | 92.91                            |

---