# Dataframes mit Join über Indexmenge zufammenführen

wenn wir Dataframes nicht über die Spalten wie bei `merge`, sondern über die Indexmenge zusammenführen wollen, bietet sich die Methode `join` an. Wenn wir also in den beiden Dataframes keine Spalten haben, die wir mit `on` ansprechen können, können wir `merge` nicht nutzen.

Im folgenden Beispiel haben wir zwei Dataframes mit jeweils einer Spalte. Darüberhinaus teilen sie eine Indexmenge, die sich allerdings leicht unterscheidet.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_left = pd.DataFrame({
    "motor": ["A1", "A2", "A3", "A4"],
},
index = ["A", "B", "C", "D"],
)


df_right = pd.DataFrame({
    "acc": [3, 2, 5, 2],
},
index = ["A", "B", "C", "E"],

)

display(df_left)
display(df_right)

  motor
A    A1
B    A2
C    A3
D    A4

   acc
A    3
B    2
C    5
E    2

### inner Join
nur die Indexe, die beide DFs haben, bleiben erhalten (A, B, C).

In [3]:
# left join
df_leftjoin = df_left.join(df_right)
df_leftjoin

  motor  acc
A    A1  3.0
B    A2  2.0
C    A3  5.0
D    A4  NaN

In [4]:
# inner join
df_inner = df_left.join(df_right, how="inner")
df_inner

  motor  acc
A    A1    3
B    A2    2
C    A3    5

In [6]:
# geht nicht, weil motor nicht in beiden Spalten enthalten ist
# merged_df = pd.merge(df_left, df_right, on="motor")

### outer Join
alle Indexe, bleiben erhalten (A, B, C, D, E). Es ergeben sie Nan-Werte

In [7]:
# outer join
df_outer = df_left.join(df_right, how="outer")
df_outer

  motor  acc
A    A1  3.0
B    A2  2.0
C    A3  5.0
D    A4  NaN
E   NaN  2.0

### right Join
alle Indexe des rechten Dataframes bleiben erhalten. Für den linken Dataframe ergeben sich Nan-Werte.

In [8]:
# right join
df_right = df_left.join(df_right, how="right")
df_right

  motor  acc
A    A1    3
B    A2    2
C    A3    5
E   NaN    2