# Arbeiten mit Pandas DataFrame (Indexing, Slicing)
Wir erstellen uns einen Test-Dataframe mit 4 Spalten

In [1]:
import numpy as np
import pandas as pd
np.random.seed(42)

# Test-Dataframe erstellen mit fortlaufendem alphabetischen Index (A, B, C ...)

In [2]:
columns = ["AK", "BE", "CO", "DI"]
values = np.random.uniform(low=2, high=4, size=(10, len(columns)))  # np.ndarray => shape(10,4)
index = [chr(i) for i in range(65, 65 + values.shape[0])]

df = pd.DataFrame(values, columns=columns, index=index)
df.head(4)

         AK        BE        CO        DI
A  2.749080  3.901429  3.463988  3.197317
B  2.312037  2.311989  2.116167  3.732352
C  3.202230  3.416145  2.041169  3.939820
D  3.664885  2.424678  2.363650  2.366809

## DataFrame Info
Um allgemeine Informationen wie Speicherbedarf über einen DataFrame zu erhalten, gibt es die Methode info

In [7]:
# info
df.info(), "***************************************", df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, A to J
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AK      10 non-null     float64
 1   BE      10 non-null     float64
 2   CO      10 non-null     float64
 3   DI      10 non-null     float64
dtypes: float64(4)
memory usage: 400.0+ bytes

(None,
 '***************************************',
               AK         BE         CO         DI
 count  10.000000  10.000000  10.000000  10.000000
 mean    3.218946   3.148776   3.071981   2.809686
 std     0.627395   0.565892   0.512427   0.571014
 min     2.238768   2.174446   2.139646   2.088804
 25%     2.685936   2.721405   2.759691   2.242240
 50%     3.490560   3.145808   3.169846   2.926165
 75%     3.715479   3.680565   3.323736   3.185115
 max     3.846050   3.846669   3.982694   3.750401)

## Dataframe kopieren
Wenn wir einen Dataframe kopieren wollen, reicht es nicht, ihn einer neuen Variable zuzuweisen. Dieses Verhalten entspricht den veränderbaren Datentypen in Python wie Liste oder Dictionary. Zum Kopieren nutzen wir die Methode `copy`

In [3]:
# Dataframe kopieren und neuer Variablen zuweisen
df_copy = df.copy() # eine Kopie des DF (deepcopy)
df_copy.AK = 1
df_copy

   AK        BE        CO        DI
A   1  3.901429  3.463988  3.197317
B   1  2.311989  2.116167  3.732352
C   1  3.416145  2.041169  3.939820
D   1  2.424678  2.363650  2.366809
E   1  3.049513  2.863890  2.582458
F   1  2.278988  2.584289  2.732724
G   1  3.570352  2.399348  3.028469
H   1  2.092901  3.215090  2.341048
I   1  3.897771  3.931264  3.616795
J   1  2.195344  3.368466  2.880305

In [4]:
# unveränderter Dataframe df
df

         AK        BE        CO        DI
A  2.749080  3.901429  3.463988  3.197317
B  2.312037  2.311989  2.116167  3.732352
C  3.202230  3.416145  2.041169  3.939820
D  3.664885  2.424678  2.363650  2.366809
E  2.608484  3.049513  2.863890  2.582458
F  3.223706  2.278988  2.584289  2.732724
G  2.912140  3.570352  2.399348  3.028469
H  3.184829  2.092901  3.215090  2.341048
I  2.130103  3.897771  3.931264  3.616795
J  2.609228  2.195344  3.368466  2.880305

# Spalten eines Dataframes

## Spaltennamen umbenennen
Wir können die Spaltennamen entweder beim Erstellen des DataFrames oder später umbenennen

In [18]:
d = {
    "a": [2, 3],
    "b": [33, 123],
    "c": [0.3, 0.234]
}
# DataFrame erstellen und via rename die Spalten umbenennen
df_name = pd.DataFrame(d)
df_namex = df_name.rename(columns={"a": "AK47", "b": "BEER", "c": "COKE"})

# alternative -------------------- #
# df_namex = df_name.rename(columns={"a": "AK47", "b": "BEER", "c": "COKE"}, inplace=True) ####

print("D: ", d, "\n\n", "name: \n", df_name, "\n\n", df_namex)

D:  {'a': [2, 3], 'b': [33, 123], 'c': [0.3, 0.234]}

 name:
    a    b      c
0  2   33  0.300
1  3  123  0.234

    AK47  BEER   COKE
0     2    33  0.300
1     3   123  0.234

## Spaltenamen umbennen mit replace

In [20]:
# rename: wir wollen das "_1" in den Spaltennamen löschen. Dazu können wir auch mit der String-Methode replace arbeiten
d = {
    "a_1": [2, 3],
    "b_1": [33, 123],
    "c_1": [0.3, 0.234]
}

df_2 = pd.DataFrame(d)
df_2.columns = df_2.columns.str.replace("_1", "")    # string accessor
print("df_2: \n", df_2)

df_2:
    a    b      c
0  2   33  0.300
1  3  123  0.234

## Spaltennamen umbennen mit list comprehensions

In [ ]:
# rename: wir wollen das nur den ersten Teil des Dictionary-Keys als Spaltenname haben. 
# Und diesen normalisiert als lowercase
d = {
    "a 32": [2, 3],
    "B 3": [33, 123],
    "c 232": [0.3, 0.234]
}

# als list comprehension

# als vektorisierte Pandas-Style Variante mit String-Operationen

## eine Spalte adressieren
Eine Spalte eines DataFrames ist eine Pandas Series

In [5]:
# Zugriff aus Spalte AK
ak_series = df.AK
ak_series.values

array([2.74908024, 2.31203728, 3.20223002, 3.66488528, 2.60848449,
       3.22370579, 2.91213997, 3.18482914, 2.13010319, 2.60922754])

## zwei Spalten adressieren und Wertzuweisung
Werden zwei oder mehr Spalten adressiert, ergibt sich wieder ein Dataframe. Die gewählten Spalten müssen natürlich nicht nebeneinanderliegen.

In [6]:
# zwei Spalten selektieren und Werte zuweisen
df_sub = df[["AK", "DI"]]
df_sub

         AK        DI
A  2.749080  3.197317
B  2.312037  3.732352
C  3.202230  3.939820
D  3.664885  2.366809
E  2.608484  2.582458
F  3.223706  2.732724
G  2.912140  3.028469
H  3.184829  2.341048
I  2.130103  3.616795
J  2.609228  2.880305

### Spalte zu neuem Index machen

In [7]:
d = {
    "a": [2, 33],
    "b": [2, 123],
    "c": [2, 0.234]
}
x = pd.DataFrame(d)
print(x)

    a    b      c
0   2    2  2.000
1  33  123  0.234

### Spalte zu Index machen 
die Spalte a soll nun zum neuen Index werden. Damit hat das Dataframe 
nur noch zwei Spalten

In [8]:
# Spalte b soll der neue Index sein
x_new_index = x.set_index("b")
x_new_index

      a      c
b
2     2  2.000
123  33  0.234

In [9]:
# Shape von x ausgeben
x_new_index.shape

(2, 2)

## Zeilen und Spalten slicen mit iloc (Index-Slicen)
Mit der Methode iloc lassen sich Dataframes nach Zeilen und Spalten slicen bzw. indizieren. Dafür übergibt man für die Zeilen und Spalten jeweils Indizies bzw. Slicing-Operationen. .iloc ist eine positionsbasierte Indexierungsmethode in Pandas, mit der Sie Daten anhand ihrer numerischen Position (ähnlich wie in Listen oder Arrays) ansprechen können.

### Was ist `.iloc` in Pandas?

`.iloc` ist eine **positionsbasierte Indexierungsmethode** in Pandas, mit der Sie Daten anhand ihrer **numerischen Position** (ähnlich wie in Listen oder Arrays) ansprechen können.

---

### **Eigenschaften von `.iloc`**
1. **Positionsbasiert:** `.iloc` verwendet **numerische Indizes**, die bei 0 beginnen.
2. **Zugriff auf Zeilen und Spalten:** Sie können Zeilen, Spalten oder bestimmte Werte basierend auf ihrer Position auswählen.
3. **Flexibel:** Unterstützt verschiedene Zugriffsarten wie einzelne Werte, Bereiche, Listen von Indizes und sogar Bedingungen.

---

### **Grundlegender Syntax**

```python
# Allgemeine Syntax
df.iloc[row_index, column_index]
```

- `row_index`: Position der Zeile, die Sie ansprechen wollen.
- `column_index`: Position der Spalte, die Sie ansprechen wollen.
- Beides beginnt bei 0.

---

### **Beispiele für `.iloc`**

#### **1. Zugriff auf eine bestimmte Zeile oder Spalte**
```python
import pandas as pd

# Beispiel-DataFrame
data = {'A': [10, 20, 30], 'B': [40, 50, 60]}
df = pd.DataFrame(data)

# Zugriff auf die 2. Zeile (Index 1)
print(df.iloc[1])  # Ausgabe: Zeile 1 (20, 50)

# Zugriff auf die 1. Spalte (Index 0)
print(df.iloc[:, 0])  # Ausgabe: Spalte A
```

#### **2. Zugriff auf ein bestimmtes Element**
```python
# Zugriff auf die Zelle in Zeile 2, Spalte 1
print(df.iloc[1, 0])  # Ausgabe: 20
```

#### **3. Zugriff auf mehrere Zeilen oder Spalten (mit Listen oder Bereichen)**
```python
# Zugriff auf Zeilen 1 bis 2 (ausschließlich 3)
print(df.iloc[1:3])

# Zugriff auf die Spalten 0 und 1
print(df.iloc[:, [0, 1]])
```

#### **4. Zugriff mit negativen Indizes**
```python
# Zugriff auf die letzte Zeile
print(df.iloc[-1])  # Ausgabe: (30, 60)
```

---

In [37]:
# iloc -Beispiele
display(df)
print("-----")
display(df.iloc[1])
series = df.iloc[1]          # ganze Zeile eines DF erzeugt eine Series
type(series)                 # Datentyp ist pd.Series

# aus einer Series lässt sich per .values ein Numpy Array erzeugen
display(series.values)       # array([2.60403724, 3.68872884, 3.03697188, 2.16305013])
display(series.index)        # Index(['AK', 'BE', 'CO', 'DI'], dtype='str')

         AK        BE        CO        DI
A  2.238768  2.636423  2.139646  2.479811
B  2.604037  3.688729  3.036972  2.163050
C  3.598013  3.090236  3.330355  3.750401
D  3.846050  2.694749  3.413471  2.088804
E  3.383108  3.697686  3.303876  3.239043
F  2.363090  3.656074  3.302721  3.357288
G  2.931634  2.174446  2.720337  2.950855
H  3.800867  3.846669  3.982694  2.142804
I  3.704875  3.201380  2.611989  2.901475
J  3.719014  2.801374  2.877753  3.023333

-----

AK    2.604037
BE    3.688729
CO    3.036972
DI    2.163050
Name: B, dtype: float64

array([2.60403724, 3.68872884, 3.03697188, 2.16305013])

Index(['AK', 'BE', 'CO', 'DI'], dtype='object')

In [50]:
print(df.iloc[: , [0,2]])

         BE        CO
A  2.636423  2.139646
B  3.688729  3.036972
C  3.090236  3.330355
D  2.694749  3.413471
E  3.697686  3.303876
F  3.656074  3.302721
G  2.174446  2.720337
H  3.846669  3.982694
I  3.201380  2.611989
J  2.801374  2.877753

# Aufgabe:

- Extrahiere die 1-2 Zeile und die 3-4 Spalte des Dataframes.
- Konvertiere alle Spalten zu float32.

In [23]:
d = {
    "a": [2, 3, 3, 2, 1, 33],
    "b": [33, 123, 23, 23, 12, 99],
    "c": [0.3, 0.234, 0.2, 0.1, 0.2, 0.99],
    "d": [0.13, 0.1234, 1.2, 0.1, 0.2, 0.99],
    "e": [1.3, 1.234, 0.2, 0.9, 0.2, 0.99],
}
# Erstelle DataFrame und extrahiere 1-2 Zeile (index 0 - 1) und 4-5 Spalte (index 3 - 4)
# Das Ergebnis sollte so aussehen:
# 0.1300  1.300
# 0.1234  1.234

# Happy Coding! 5 Minuten Zeit
print("d: \n", d)
print()

# create DF
df_aufgabe = pd.DataFrame(d)

# extraer sub dataframe
df_sub = df_aufgabe.iloc[0:2, 3:5]

# convertir a float32
df_float = df_aufgabe.astype("float32")
print()
print("DataFrame: \n", df_aufgabe)
print()
print("Sub: \n", df_sub)
print()
print("float: \n", df_float)
print()
print("types: \n", df_aufgabe.dtypes)
print()
print("types: \n", df_sub.dtypes)

d:
 {'a': [2, 3, 3, 2, 1, 33], 'b': [33, 123, 23, 23, 12, 99], 'c': [0.3, 0.234, 0.2, 0.1, 0.2, 0.99], 'd': [0.13, 0.1234, 1.2, 0.1, 0.2, 0.99], 'e': [1.3, 1.234, 0.2, 0.9, 0.2, 0.99]}


DataFrame:
     a    b      c       d      e
0   2   33  0.300  0.1300  1.300
1   3  123  0.234  0.1234  1.234
2   3   23  0.200  1.2000  0.200
3   2   23  0.100  0.1000  0.900
4   1   12  0.200  0.2000  0.200
5  33   99  0.990  0.9900  0.990

Sub:
         d      e
0  0.1300  1.300
1  0.1234  1.234

float:
       a      b      c       d      e
0   2.0   33.0  0.300  0.1300  1.300
1   3.0  123.0  0.234  0.1234  1.234
2   3.0   23.0  0.200  1.2000  0.200
3   2.0   23.0  0.100  0.1000  0.900
4   1.0   12.0  0.200  0.2000  0.200
5  33.0   99.0  0.990  0.9900  0.990

types:
 a      int64
b      int64
c    float64
d    float64
e    float64
dtype: object

types:
 d    float64
e    float64
dtype: object

## Zeilen und Spalten slicen mit loc (Label-Slicen)
Mit loc lässt sich über die Spaltennamen und Indexnamen slicen

### **Vergleich `.iloc` vs. `.loc`**


| Feature               | `.iloc`                        | `.loc`                       |
|-----------------------|---------------------------------|------------------------------|
| **Indexart**          | Positionsbasiert (numerisch)   | Labelbasiert (z. B. Namen)   |
| **Syntax**            | `iloc[row, col]`               | `loc[row_label, col_label]`  |
| **Beispiele**         | `iloc[0, 1]`                   | `loc['Zeile1', 'SpalteB']`   |
| **Negative Indizes**  | Unterstützt                    | Nicht unterstützt            |

In [64]:
print(df)
print("-----")
print("todas las filas UND las columnas AK & DI \n", df.loc[:, ["AK", "DI"]])
print("-----")
print("todas las filas UND columnas de AK a CO \n", df.loc[:, "AK":"CO"])
print("-----")
print("solo las primeras 3 (tres) filas y columnas AK & DI \n", df.loc["A":"C", ["AK", "DI"]])
print("-----")

         AK        BE        CO        DI
A  2.238768  2.636423  2.139646  2.479811
B  2.604037  3.688729  3.036972  2.163050
C  3.598013  3.090236  3.330355  3.750401
D  3.846050  2.694749  3.413471  2.088804
E  3.383108  3.697686  3.303876  3.239043
F  2.363090  3.656074  3.302721  3.357288
G  2.931634  2.174446  2.720337  2.950855
H  3.800867  3.846669  3.982694  2.142804
I  3.704875  3.201380  2.611989  2.901475
J  3.719014  2.801374  2.877753  3.023333
-----
todas las filas UND las columnas AK & DI
          AK        DI
A  2.238768  2.479811
B  2.604037  2.163050
C  3.598013  3.750401
D  3.846050  2.088804
E  3.383108  3.239043
F  2.363090  3.357288
G  2.931634  2.950855
H  3.800867  2.142804
I  3.704875  2.901475
J  3.719014  3.023333
-----
todas las filas UND columnas de AK a CO
          AK        BE        CO
A  2.238768  2.636423  2.139646
B  2.604037  3.688729  3.036972
C  3.598013  3.090236  3.330355
D  3.846050  2.694749  3.413471
E  3.383108  3.697686  3.303876
F  2.363090  3.656074  3.302721
G  2.931634  2.174446  2.720337
H  3.800867  3.846669  3.982694
I  3.704875  3.201380  2.611989
J  3.719014  2.801374  2.877753
-----
solo las primeras 4 filas y columnas AK & DI
          AK        DI
A  2.238768  2.479811
B  2.604037  2.163050
C  3.598013  3.750401
-----

## Slicing und neue Zuweisung
Wir können den Slicing-Operator im Zusammenhang mit `loc` auch nutzen, um neue Zuweisungen zu machen.

In [65]:
# wir setzen in den Zeilen mit index A und C den Spaltenwert AK auf 99 
df.loc[["A", "C"], ["AK"]] = 99

# wir setzen in den Zeilen mit Indizies [A, B] die Spaltenwerte BE und CO auf 123
df.loc[["A", "B"], ["BE", "CO"]] = 123
df

# wir setzen in den Zeilen mit Indizies A und B den Spaltenwert BE auf die Summe von DI und AK
df.loc[["A", "B"], ["BE"]] = df.loc[["A", "B"], "DI"] + df.loc[["A", "B"], "AK"]
df

          AK          BE          CO        DI
A  99.000000  101.479811  123.000000  2.479811
B   2.604037    4.767087  123.000000  2.163050
C  99.000000    3.090236    3.330355  3.750401
D   3.846050    2.694749    3.413471  2.088804
E   3.383108    3.697686    3.303876  3.239043
F   2.363090    3.656074    3.302721  3.357288
G   2.931634    2.174446    2.720337  2.950855
H   3.800867    3.846669    3.982694  2.142804
I   3.704875    3.201380    2.611989  2.901475
J   3.719014    2.801374    2.877753  3.023333

## Alle Zeilen, die den Index B, E oder H haben

In [20]:
df.loc[["B", "E", "H"]]

         AK        BE        CO        DI
B  2.312037  2.311989  2.116167  3.732352
E  2.608484  3.049513  2.863890  2.582458
H  3.184829  2.092901  3.215090  2.341048