# Spalten im Dataframe
Wir erstellen uns einen Test-Dataframe mit 4 Spalten

In [2]:
import numpy as np
import pandas as pd
np.random.seed(42)

# Spaltennamen passend zur Ölindustrie
columns = ["Förderrate (bbl/d)", "Druck (psi)", "Viskosität (cP)", "Wassertiefe (m)"]

# Zufällige Werte zwischen 2 und 4 erzeugen
values = np.random.uniform(low=2, high=4, size=(10, 4))

# Index als Buchstaben A-J
index = [chr(i) for i in range(65, 65 + values.shape[0])]

# DataFrame erstellen
df = pd.DataFrame(values, columns=columns, index=index)

# Werte skalieren, um realistischere Größenordnungen für die Ölindustrie zu erhalten
df = df * [1000, 5000, 14, 200]

# Neue Spalte mit doppelten/dreifachen Werten hinzufügen
df["Bohrloch-ID"] = ["A1", "A1", "B2", "B2", "B2", "C3", "C3", "D4", "E5", "E5"]

# df = df.drop_duplicates(subset=["Bohrloch-ID", "Wassertiefe (m)"]) 

df

,Förderrate (bbl/d),Druck (psi),Viskosität (cP),Wassertiefe (m),Bohrloch-ID
A,2749.080238,19507.143064,48.495830,639.463394,A1
B,2312.037281,11559.945203,29.626341,746.470458,A1
C,3202.230023,17080.725778,28.576366,787.963941,B2
D,3664.885282,12123.391107,33.091099,473.361804,B2
E,2608.484486,15247.564316,40.094461,516.491656,B2
F,3223.705789,11394.938607,36.180050,546.544737,C3
G,2912.139968,17851.759614,33.590866,605.693775,C3
H,3184.829138,10464.504127,45.011256,468.209649,D4
I,2130.103186,19488.855373,55.037697,723.358939,E5
J,2609.227538,10976.721140,47.158525,576.060997,E5

## Die Anzahl an Elementen einer Spalte (Länge)
Für diese Aufgabe kann die Python-Funktion len genommen werden. Besser ist aber das Ermitteln der Dimension mit `shape`. Das erste Element von shape ist immer die Anzahl der Zeilen und damit der Einträge der Spalte (Spaltenlänge).

In [3]:
# via len Die Anzahl der Elemente einer Spalte ausgeben
len(df)

10

In [4]:
# via shape den Shape der Spalte (Series) ausgeben
df.shape[0]

10

## Eindeutige Werte in einer Spalte
mit `unique` lassen sich eindeutige Werte in einer Spalte identifizieren.

In [5]:
# unique
print(df["Bohrloch-ID"].unique())
print()

# df.value_counts() zählt die eindeutigen Zeilen im DataFrame und gibt die Häufigkeit jeder Zeile zurück.
# macht in dem Beispiel wenig Sinn, da kontinuierliche (an der Zahl rechts sieht man die Häufigkeit)
print(df.value_counts())
# series.value_counts()
print()

print(df["Bohrloch-ID"].value_counts())

['A1' 'B2' 'C3' 'D4' 'E5']

Förderrate (bbl/d)  Druck (psi)   Viskosität (cP)  Wassertiefe (m)  Bohrloch-ID
2130.103186         19488.855373  55.037697        723.358939       E5             1
2312.037281         11559.945203  29.626341        746.470458       A1             1
2608.484486         15247.564316  40.094461        516.491656       B2             1
2609.227538         10976.721140  47.158525        576.060997       E5             1
2749.080238         19507.143064  48.495830        639.463394       A1             1
2912.139968         17851.759614  33.590866        605.693775       C3             1
3184.829138         10464.504127  45.011256        468.209649       D4             1
3202.230023         17080.725778  28.576366        787.963941       B2             1
3223.705789         11394.938607  36.180050        546.544737       C3             1
3664.885282         12123.391107  33.091099        473.361804       B2             1
Name: count, dtype: int64

Bohrloch-ID
B2    3
A1    2
C3    2
E5    2
D4    1
Name: count, dtype: int64

## numerische Spalte in Numpy Array umformen
Wir können mit der Methode to_numpy() eine Spalte in einen Numpy Array umformen. Der Index geht dabei natürlich verloren.

In [6]:
# Spalte in Numpy Array konvertieren
v = df["Förderrate (bbl/d)"].to_numpy()
M = df.to_numpy()
print("v: \n", v)
print()
print("M: \n", M)

v:
 [2749.08023769 2312.03728088 3202.23002349 3664.8852816  2608.48448592
 3223.70578944 2912.13996843 3184.82913772 2130.10318597 2609.22753835]

M:
 [[2749.080237694725 19507.14306409916 48.49583037071934 639.4633936788147
  'A1']
 [2312.037280884873 11559.945203362027 29.626341140709588
  746.470458309974 'A1']
 [3202.2300234864174 17080.725777960455 28.57636584028247
  787.9639408647977 'B2']
 [3664.8852816008434 12123.391106782761 33.091099081798816
  473.3618039413735 'B2']
 [2608.4844859190753 15247.56431632238 40.09446052197924
  516.4916560792168 'B2']
 [3223.7057894447594 11394.93860652042 36.180050158986106
  546.5447373174767 'C3']
 [2912.1399684340718 17851.759613930135 33.59086590043407
  605.6937753654447 'C3']
 [3184.8291377240853 10464.504127199978 45.01125585324027
  468.20964947491655 'D4']
 [2130.103185970559 19488.855372533333 55.03769692608766
  723.3589392465844 'E5']
 [2609.2275383467413 10976.721140063839 47.15852474234039
  576.0609974958405 'E5']]

## alle Spalten eines Dataframes in Numpy Array umformen

In [7]:
# neuen Dataframe mit iloc erstellen und nach Numpy umformen. Ergibt zweidimensionale Datenstruktur
df_ausschnitt = df.iloc[0:2, :-1]
print("1: \n", df_ausschnitt)
df_ausschnitt.to_numpy()
print()
print("2: \n", df_ausschnitt)

1:
    Förderrate (bbl/d)   Druck (psi)  Viskosität (cP)  Wassertiefe (m)
A         2749.080238  19507.143064        48.495830       639.463394
B         2312.037281  11559.945203        29.626341       746.470458

2:
    Förderrate (bbl/d)   Druck (psi)  Viskosität (cP)  Wassertiefe (m)
A         2749.080238  19507.143064        48.495830       639.463394
B         2312.037281  11559.945203        29.626341       746.470458

## Iteration über Dataframe und Spalten
Das Iterieren über Dataframe und Series ist möglich, aber in Pandas nicht sonderlich üblich, da unperformant. Vektorisierung ist ein sehr viel besseres Verfahren, um (parallel) Werte in einer Datenstruktur zu verändern. Moderne CPUs unterstüzten Vektorisierung. Mehr dazu in den weiteren Kapiteln.

### Iteration über einen Dataframe. Jede Row is ein String mit dem Spaltennamen

In [8]:
for column_name in df:
    print(column_name)

Förderrate (bbl/d)
Druck (psi)
Viskosität (cP)
Wassertiefe (m)
Bohrloch-ID

### Iteration über alle Zeilen eines Dataframes

In [9]:
for columnname, series in df.iterrows():
    print(columnname)

A
B
C
D
E
F
G
H
I
J

### Iteration über die Werte einer Spalte (Pandas Series)

In [10]:
for row in df["Bohrloch-ID"]:
    print(row)

A1
A1
B2
B2
B2
C3
C3
D4
E5
E5

### Iteration über die Spalte mit iteritems
mit der Methode iteritems bekommen wir einen Tupel aus Spaltenname, Wert pro Spaltenwert

In [11]:
for x in df["Bohrloch-ID"].items():
    print(x)

('A', 'A1')
('B', 'A1')
('C', 'B2')
('D', 'B2')
('E', 'B2')
('F', 'C3')
('G', 'C3')
('H', 'D4')
('I', 'E5')
('J', 'E5')

In [12]:
# Iteration über die Spalten der Zeile 0
for cols in df.iloc[0]:
    print(cols)

2749.080237694725
19507.14306409916
48.49583037071934
639.4633936788147
A1

In [13]:
for index, bohrloch_id in df["Bohrloch-ID"].items():
    print(index, bohrloch_id)

A A1
B A1
C B2
D B2
E B2
F C3
G C3
H D4
I E5
J E5

## Spalten löschen

In [14]:
## drop (con: inplace= True, no se genera DataFrame nuevo
df_neu = df.drop(columns=["Förderrate (bbl/d)", "Bohrloch-ID"])
print("df_neu", df_neu)

df_neu     Druck (psi)  Viskosität (cP)  Wassertiefe (m)
A  19507.143064        48.495830       639.463394
B  11559.945203        29.626341       746.470458
C  17080.725778        28.576366       787.963941
D  12123.391107        33.091099       473.361804
E  15247.564316        40.094461       516.491656
F  11394.938607        36.180050       546.544737
G  17851.759614        33.590866       605.693775
H  10464.504127        45.011256       468.209649
I  19488.855373        55.037697       723.358939
J  10976.721140        47.158525       576.060997

## Zeilen löschen

In [15]:
## via index drop
df_cleaned = df.drop(index=["B", "E"])
print("df_cleaned: \n", df_cleaned)

df_cleaned:
    Förderrate (bbl/d)   Druck (psi)  Viskosität (cP)  Wassertiefe (m)  \
A         2749.080238  19507.143064        48.495830       639.463394
C         3202.230023  17080.725778        28.576366       787.963941
D         3664.885282  12123.391107        33.091099       473.361804
F         3223.705789  11394.938607        36.180050       546.544737
G         2912.139968  17851.759614        33.590866       605.693775
H         3184.829138  10464.504127        45.011256       468.209649
I         2130.103186  19488.855373        55.037697       723.358939
J         2609.227538  10976.721140        47.158525       576.060997

  Bohrloch-ID
A          A1
C          B2
D          B2
F          C3
G          C3
H          D4
I          E5
J          E5

## Duplikate löschen

mit drop_duplicates lassen sich zeilenweise Duplikate löschen.

In [16]:
# drop dublicates
df.loc[:, "field"] = np.random.randint(1, 3, size=df.shape[0])
df

,Förderrate (bbl/d),Druck (psi),Viskosität (cP),Wassertiefe (m),Bohrloch-ID,field
A,2749.080238,19507.143064,48.495830,639.463394,A1,1
B,2312.037281,11559.945203,29.626341,746.470458,A1,2
C,3202.230023,17080.725778,28.576366,787.963941,B2,1
D,3664.885282,12123.391107,33.091099,473.361804,B2,2
E,2608.484486,15247.564316,40.094461,516.491656,B2,1
F,3223.705789,11394.938607,36.180050,546.544737,C3,1
G,2912.139968,17851.759614,33.590866,605.693775,C3,2
H,3184.829138,10464.504127,45.011256,468.209649,D4,1
I,2130.103186,19488.855373,55.037697,723.358939,E5,2
J,2609.227538,10976.721140,47.158525,576.060997,E5,2

In [17]:
display(df)
df.drop_duplicates(subset=["Bohrloch-ID", "field"])

,Förderrate (bbl/d),Druck (psi),Viskosität (cP),Wassertiefe (m),Bohrloch-ID,field
A,2749.080238,19507.143064,48.495830,639.463394,A1,1
B,2312.037281,11559.945203,29.626341,746.470458,A1,2
C,3202.230023,17080.725778,28.576366,787.963941,B2,1
D,3664.885282,12123.391107,33.091099,473.361804,B2,2
E,2608.484486,15247.564316,40.094461,516.491656,B2,1
F,3223.705789,11394.938607,36.180050,546.544737,C3,1
G,2912.139968,17851.759614,33.590866,605.693775,C3,2
H,3184.829138,10464.504127,45.011256,468.209649,D4,1
I,2130.103186,19488.855373,55.037697,723.358939,E5,2
J,2609.227538,10976.721140,47.158525,576.060997,E5,2

,Förderrate (bbl/d),Druck (psi),Viskosität (cP),Wassertiefe (m),Bohrloch-ID,field
A,2749.080238,19507.143064,48.495830,639.463394,A1,1
B,2312.037281,11559.945203,29.626341,746.470458,A1,2
C,3202.230023,17080.725778,28.576366,787.963941,B2,1
D,3664.885282,12123.391107,33.091099,473.361804,B2,2
F,3223.705789,11394.938607,36.180050,546.544737,C3,1
G,2912.139968,17851.759614,33.590866,605.693775,C3,2
H,3184.829138,10464.504127,45.011256,468.209649,D4,1
I,2130.103186,19488.855373,55.037697,723.358939,E5,2